# Site settings
title: Le Guan 
email: guanle.ustc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Le Guan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guanle.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Postdoctoral Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
google_scholar: gz-6ugcAAAAJ
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"
github_username:  guanleustc
twitter_username: guanlelennon

gems:
  - jekyll-sitemap

#theme: jekyll-theme-midnight
#name: Le
#markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
